name: tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pipenv
          # Not using `--deploy` here. Updates should be handled by a bot.
          pipenv install --dev
      - name: Run tests
        run: |
          pipenv run pytest
